import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { Toaster } from 'react-hot-toast';
import Providers from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <GoogleOAuthProvider clientId="730325407157-775dsanacqeau8u8m2bfvgur79h2c4gd.apps.googleusercontent.com">
    <html lang="en">
        <div>
          <Toaster />
          <body className={inter.className}> <Providers>{children}</Providers></body>
        </div>
    </html>
    </GoogleOAuthProvider>
  );
}