import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

import { GoogleOAuthProvider } from '@react-oauth/google';
import { Toaster } from 'react-hot-toast';
import { AppProps } from "next/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient()


export default function App({
  Component, pageProps
}: AppProps<{
  children: React.ReactNode;
}>) {
  return (

    <QueryClientProvider client={queryClient}>
    <GoogleOAuthProvider clientId="730325407157-775dsanacqeau8u8m2bfvgur79h2c4gd.apps.googleusercontent.com">
      {/* <html lang="en"> */}
      <Toaster />
      <Component {...pageProps} />
      {/* <body className={inter.className}>{children}</body> */}
      {/* <ReactQueryDevtools initialIsOpen={false} /> */}

      {/* </html> */}
    </GoogleOAuthProvider>
    </QueryClientProvider>
  );
}
